// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.AppView = (function(superClass) {
  extend(AppView, superClass);

  function AppView() {
    return AppView.__super__.constructor.apply(this, arguments);
  }

  AppView.prototype.template = _.template('<div class="buttons-container"></div> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div> <div class="chips-container"></div>');

  AppView.prototype.buttonsTemplate = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button>');

  AppView.prototype.gameOverTemplate = _.template('<button class="new-game">New Game</button> <span class="message"><%= message %></span>');

  AppView.prototype.events = {
    'click .hit-button': function() {
      return this.model.get('game').get('playerHand').hit();
    },
    'click .stand-button': function() {
      return this.model.get('game').get('playerHand').stand();
    },
    'click .new-game': function() {
      return this.renderNewGame();
    }
  };

  AppView.prototype.renderNewGame = function() {
    this.model.newGame();
    this.render();
    return this.model.get('game').on('change:winner', function() {
      return setTimeout((function(_this) {
        return function() {
          return _this.$('.buttons-container').html(_this.gameOverTemplate(_this.model.get('game').attributes));
        };
      })(this), 1200);
    }, this);
  };

  AppView.prototype.initialize = function() {
    return this.renderNewGame();
  };

  AppView.prototype.render = function() {
    this.$el.children().detach();
    this.$el.html(this.template);
    this.$('.buttons-container').html(this.buttonsTemplate);
    this.$('.player-hand-container').html(new HandView({
      collection: this.model.get('game').get('playerHand')
    }).el);
    return this.$('.dealer-hand-container').html(new HandView({
      collection: this.model.get('game').get('dealerHand')
    }).el);
  };

  return AppView;

})(Backbone.View);
